image: maven:latest

pages:
  stage: deploy
  script:
    - mvn javadoc:aggregate # Generate Javadocs
    - mkdir public          # GitLab Pages requires your site to be in a 'public' directory
    - cp -r target/site/apidocs/* public  # Copy Javadocs to the 'public' directory
  artifacts:
    paths:
      - public
  only:
    - main   # You can specify the branches you want this job to run on, this example uses main branch
